repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=50000']
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
    - id: mixed-line-ending
      args: ['--fix=lf']

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: Sort imports with isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      name: Autoformat with black
      args: [-t, py38, -l, "100"]
      additional_dependencies: [ipython, tokenize-rt]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-isort
        name: Format notebooks; sort imports by isort
        files: notebooks

      - id: nbqa-black
        name: Format notebooks; reformat by black
        files: notebooks

      - id: nbqa-pyupgrade
        files: notebooks
        name: Format notebooks; upgrade syntax to Python 3.7+ by pyupgrade

      - id: nbqa-flake8
        name: Format notebooks; lint with flake8
        files: notebooks
