repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.9
    hooks:
      - id: nbqa-isort
        name: Format notebooks; sort imports by isort
        files: notebooks
        args: [--nbqa-mutate]

      - id: nbqa-black
        name: Format notebooks; reformat by black
        files: notebooks
        args: [--nbqa-mutate]

      - id: nbqa-pyupgrade
        files: notebooks
        name: Format notebooks; upgrade syntax to Python 3.6+ by pyupgrade
        args: [--nbqa-mutate]
