name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9

  # hyriver packages
  - async_retriever=0.2.5
  - pygeoogc=0.11.7
  - pygeoutils=0.11.7
  - py3dep=0.11.4
  - pynhd=0.11.4
  - pygeohydro=0.11.3
  - pydaymet=0.11.4

  # optional deps to speed up xarray and geopandas
  - bottleneck
  - pygeos

  # Other third-party deps
  - cartopy
  - mapclassify
  - contextily
  - colorcet
  - geoviews
  - hvplot
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets
