name: binder
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.11

# HyRiver packages
- async-retriever >=0.16
- pygeoogc >=0.16
- pygeoutils >=0.16
- py3dep >=0.16
- pynhd >=0.16.1
- hydrosignatures >=0.16
- pygeohydro >=0.16
- pydaymet >=0.16
- pygridmet >=0.16
- pynldas2 >=0.16

# optional HyRiver deps
- numba
- planetary-computer
- pystac-client
- pyogrio >=0.5.0
- py7zr
- pyflwdir >=0.5.6

# optional deps for speeding xarray
- numbagg
- flox

# Other deps required by example notebooks
- mapclassify
- contextily
- hvplot
- osmnx
- tqdm
- pytables
- ffmpeg
- ipywidgets
- xarray-spatial
- datashader
