name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9

  # hyriver packages
  - async_retriever=0.3.1
  - pygeoogc=0.12.1
  - pygeoutils=0.12.1
  - py3dep=0.12.1
  - pynhd=0.12.1
  - pygeohydro=1.12.2
  - pydaymet=0.12.1

  # optional deps to speed up xarray and geopandas
  - bottleneck
  - pygeos

  # Other third-party deps
  - cartopy
  - mapclassify
  - contextily
  - colorcet
  - geoviews
  - hvplot
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets
  - numba
  - pygmo
