name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  # HyRiver deps
  - setuptools
  - owslib
  - defusedxml
  - requests
  - aiohttp
  - chardet
  - aiodns
  - brotlipy
  - nest-asyncio
  - xarray
  - netCDF4
  - geopandas
  - pyproj
  - pyarrow
  - rasterio
  - shapely
  - orjson
  - simplejson
  - lxml
  - openpyxl
  - dask
  - networkx
  - matplotlib-base
  - folium

  # HyRiver packages
  - pygeoogc
  - pygeoutils
  - pynhd
  - py3dep
  - pydaymet
  - pygeohydro

  # Speedups
  - bottleneck
  - pygeos

  # Other third-party deps
  - descartes
  - cartopy
  - cmocean
  - mapclassify
  - contextily
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets

