name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8

  # hyriver packages
  - async_retriever
  - pygeoogc
  - pygeoutils
  - py3dep
  - pynhd
  - pygeohydro
  - pydaymet

  # optional deps to speed up xarray and geopandas
  - bottleneck
  - pygeos

  # Other third-party deps
  - cartopy
  - cmocean
  - mapclassify
  - contextily
  - colorcet
  - geoviews
  - hvplot
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets
