name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - chardet
  - cytoolz
  - nest-asyncio
  - orjson
  - setuptools

  # pygeoogc deps
  - defusedxml
  - owslib
  - pyyaml
  - pyproj
  - requests
  - requests-cache
  - setuptools
  - shapely
  - simplejson
  - urllib3

  # pygeoutils deps
  - affine
  - geopandas
  - numpy
  - netcdf4
  - orjson
  - rasterio
  - xarray

  # pynhd deps
  - networkx
  - pandas
  - pyarrow

  # pygeohydro deps
  - folium
  - lxml
  - matplotlib-base
  - openpyxl

  # pydaymet deps
  - dask-core
  - scipy

  # optional deps to speed up xarray and geopandas
  - bottleneck
  - rtree
  - pygeos

  # HyRiver packages
  - async_retriever=0.1.0
  - pygeoogc=0.10.1
  - pygeoutils=0.10.1
  - pynhd=0.10.1
  - py3dep=0.10.1
  - pydaymet=0.10.2
  - pygeohydro=0.10.2

  # Other third-party deps
  - cartopy
  - cmocean
  - mapclassify
  - contextily
  - colorcet
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets
