name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9

  # hyriver packages
  - async_retriever=0.2.4
  - pygeoogc=0.11.5
  - pygeoutils=0.11.6
  - py3dep=0.11.3
  - pynhd=0.11.3
  - pygeohydro=0.11.2
  - pydaymet=0.11.3

  # optional deps to speed up xarray and geopandas
  - bottleneck
  - pygeos

  # Other third-party deps
  - cartopy
  - mapclassify
  - contextily
  - colorcet
  - geoviews
  - hvplot
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets
