name: binder
channels:
  - numba
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10

  # HyRiver packages
  - async_retriever>=0.3.6
  - pygeoogc>=0.13.7
  - pygeoutils>=0.13.9
  - py3dep>=0.13.7
  - pynhd>=0.13.7
  - pygeohydro>=0.13.7
  - pydaymet>=0.13.7

  # optional deps for speeding up some operations
  - bottleneck
  - numba
  - planetary-computer
  - pyogrio
  - pystac-client
  - richdem>=0.3.4


  # Other third-party deps
  - mapclassify
  - contextily
  - hvplot
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets
  - xarray-spatial
  - datashader
