name: binder
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9

  # HyRiver packages
  - async_retriever=0.3.1
  - pygeoogc=0.12.2
  - pygeoutils=0.12.2
  - py3dep=0.12.2
  - pynhd=0.12.1
  - pygeohydro=0.12.3
  - pydaymet=0.12.2

  # Optional deps to speed up xarray
  - bottleneck

  # Other third-party deps
  - cartopy
  - mapclassify
  - contextily
  - colorcet
  - geoviews
  - hvplot
  - osmnx
  - tqdm
  - pytables
  - ffmpeg
  - jupyterlab_widgets
  - ipywidgets
  - numba
  - pygmo
