[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1
flake8 = 0

[tool.nbqa.addopts]
isort = [
    "-l", "100",
    "--profile", "black",
    "--multi-line", "3",
    "--tc",
    "--up",
    "-p", "async_retriever",
    "-p", "pygeoogc",
    "-p", "pygeoutils",
    "-p", "py3dep",
    "-p", "pynhd",
    "-p", "hydrosignatures",
    "-p", "pydaymet",
    "-p", "pynldas",
    "-p", "pygeohydro",
]
black = ["-t", "py38", "-l", "100"]
pyupgrade = ["--py38-plus"]
flake8 = ["--ignore", "E203,E402,E501,E731,W503,D107,D105", "--exclude",
"__init__.py,.ipynb_checkpoints", "--max-line-length", "100"]

[tool.black]
line-length = 100

[tool.pycln]
path = "notebooks"
include="(.*\\.py|.*\\.ipynb)"
exclude="(\\.ipynb_checkpoints|__pycache__)"
expand_stars = true
verbose = true
all = true
no_gitignore = false

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = [
    "async_retriever",
    "pygeoogc",
    "pygeoutils",
    "py3dep",
    "pynhd",
    "hydrosignatures",
    "pydaymet",
    "pynldas",
    "pygeohydro",
]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100
