[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1
flake8 = 0

[tool.nbqa.addopts]
isort = [
    "-l", "100",
    "--profile", "black",
    "--multi-line", "3",
    "--tc",
    "--up",
    "-p", "async_retriever",
    "-p", "pygeoogc",
    "-p", "pygeoutils",
    "-p", "py3dep",
    "-p", "pynhd",
    "-p", "pydaymet",
    "-p", "pygeohydro",
]
black = ["-t", "py37", "-l", "100"]
pyupgrade = ["--py37-plus"]
flake8 = ["--ignore", "E203,E402,E501,E731,W503,D107,D105", "--exclude",
"__init__.py,.ipynb_checkpoints", "--max-line-length", "100"]

[tool.black]
line-length = 100
target-version = ['py37']

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = ["async_retriever", "pygeoogc", "pygeoutils", "py3dep", "pynhd", "pydaymet", "pygeohydro"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100
