[tool.ruff]
target-version = "py38"
lint.select = [
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # pydocstyle
    "D",
    # Error
    "E",
    # pyflakes
    "F",
    # isort
    "I",
    # flake8-implicit-str-concat
    "ISC",
    # pep8-naming
    "N",
    # pygrep-hooks
    "PGH",
    # flake8-pytest-style
    "PT",
    # flake8-use-pathlib
    "PTH",
    # flake8-quotes
    "Q",
    # bandit
    "S",
    # flake8-simplify
    "SIM",
    # flake8-print
    "T20",
    # tryceratops
    "TRY",
    # pyupgrade
    "UP",
    # Warning
    "W",
    # flake8-2020
    "YTT",
    # flake8-debugger
    "T10",
    # flake8-gettext
    "INT",
    # pylint
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    # misc lints
    "PIE",
    # flake8-pyi
    "PYI",
    # tidy imports
    "TID",
    # type-checking imports
    "TCH",
    # Ruff-specific rules
    "RUF",
]

exclude = [
    "__pycache__",
    ".nox",
]

lint.ignore = [
    "D103",
    "D105",
    "E501",
    "PLR2004",
    "PLR0913",
    "PGH003",
    # conflict with run-formatter
    "ISC001",
    # print statements
    "T201",
    # pickle
    "S301",
    # long msg to exceptions
    "TRY003",
    # avoid lambda
    "E731",
]
line-length = 100

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "chr",
    "typer.Argument",
    "typer.Option",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
known-first-party = [
    "async_retriever",
    "pygeoogc",
    "pygeoutils",
    "pynhd",
    "py3dep",
    "hydrosignatures",
    "pygeohydro",
    "pydaymet",
    "pygridmet",
    "pynldas2",
]

[tool.pycln]
path = "notebooks"
include="(.*\\.py|.*\\.ipynb)"
exclude="(\\.ipynb_checkpoints|__pycache__)"
expand_stars = true
verbose = true
all = true
no_gitignore = false
