name: CI

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
  pull_request:
    branches:
    - '**'
    tags-ignore:
    - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        notebook: ['3dep', 'aridity', 'classification', 'columbia', 'cross_section', 'dam_impact', 'daymet', 'flood_peak', 'geoconnex', 'hymod_calibration', 'ndvi', 'nhdplus', 'nid', 'nlcd', 'nldas', 'noaa', 'nwis', 'pet_validation', 'pygeoapi', 'rem', 'signatures', 'soil', 'ssebop', 'things', 'us_coasts', 'water_quality', 'webservices']

    steps:
    - uses: actions/checkout@v3

    - name: Set environment variables
      run: |-
        echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "CONDA_ENV_FILE=environment.yml" >> $GITHUB_ENV

    - name: Setup micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ${{ env.CONDA_ENV_FILE }}
        environment-name: binder
        cache-env: true
        cache-env-key: ${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}

    - name: Install nbmake
      run: micromamba install -y pytest nbmake
    - name: Version info
      run: |-
        python -c "import pygeohydro; pygeohydro.show_versions()"
    - name: Run nbmake
      run: |-
        python -m pytest --nbmake notebooks/${{ matrix.notebook }}.ipynb
