name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  test:
    name: ${{ matrix.notebook }} notebook
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
        notebook: ['3dep', 'aridity', 'columbia', 'cross_section', 'daymet', 'ndvi', 'nhdplus', 'nid', 'nlcd', 'noaa', 'nwis', 'pet_validation', 'pygeoapi', 'ssebop', 'us_coasts', 'webservices']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@master
      - name: Set environment variables
        run: |-
          echo "CONDA_ENV_FILE=environment.yml" >> $GITHUB_ENV
          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
      - name: Cache conda
        uses: actions/cache@v2.1.6
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-py${{ matrix.python-version }}-${{
            hashFiles('environment.yml') }}
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          channel-priority: strict
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          activate-environment: binder
          use-mamba: true
          use-only-tar-bz2: true
      - name: Install nbmake
        run: |-
          mamba info -a
          mamba list
          python -m pip install pytest nbmake
      - name: Version info
        run: |-
          python -c "import pygeohydro; pygeohydro.show_versions()"
      - name: Run nbmake
        run: |-
          python -m pytest --nbmake notebooks/${{ matrix.notebook }}.ipynb
